### ISSUE TITLE
可移动区域太小了吧

### ISSUE THREAD

**Issue by leafee98** [leafee98/BallWithInertance#2]
'(´▽｀)ノ♪'我又回来了，并且又提出了一个不太想让人解决的issue

**Comment by leafee98** [comment]
我又来假装回答了 ε٩(๑> ₃ <)۶ з
答：这个问题我也意识到了（废话！自己提的自己还不知道），改起分辨率来很麻烦的啊，随缘进行修改吧，咕咕咕～

**Comment by kailanguage** [comment]
***好想把圆撞墙的时候弄成滑稽表情***

**Comment by kailanguage** [comment]
![timg](https://user-images.githubusercontent.com/41792700/49651811-31474880-fa6b-11e8-9dea-d6ff8bf60fad.jpg)

**Comment by leafee98** [comment]
开发者无情地拒绝了您的请求![图](https://user-images.githubusercontent.com/41792700/49651811-31474880-fa6b-11e8-9dea-d6ff8bf60fad.jpg)
